blacklisted-names = ["foo", "too"]
too-many-arguments-threshold = 4
enum-variant-name-threshold = 3
single-char-binding-names-threshold = 0
cognitive-complexity-threshold = 20
max-fn-params-bools = 3
max-struct-bools = 3
too-many-lines-threshold = 30
